// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHrH_b3ystFpNHRqgFRsXv357FCbn3Sw',
    appId: '1:846745140818:web:b9db067393bcb37c7b298b',
    messagingSenderId: '846745140818',
    projectId: 'orround-62bd2',
    authDomain: 'orround-62bd2.firebaseapp.com',
    storageBucket: 'orround-62bd2.firebasestorage.app',
    measurementId: 'G-14XEGK17TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRIXm-AbiFXvsEu86yzb-qutXWyiVny8E',
    appId: '1:846745140818:android:a726e1d77101941d7b298b',
    messagingSenderId: '846745140818',
    projectId: 'orround-62bd2',
    storageBucket: 'orround-62bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvi2Pi9YDGNlF53up66-ncLq76yBC5Afo',
    appId: '1:846745140818:ios:e48f54fbb81f2cb77b298b',
    messagingSenderId: '846745140818',
    projectId: 'orround-62bd2',
    storageBucket: 'orround-62bd2.firebasestorage.app',
    iosBundleId: 'com.oranastudiomy.orround',
  );
}
